name: End-to-End Tests Workflow

on:
  push:
    branches:
      - main  # Adjust this based on your branch name

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm i
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm run codeceptjs
